/* eslint-disable @typescript-eslint/no-explicit-any */
import z from "zod";

import type { RakunOperationContractMap } from "./types";
import { defineOperationContract } from "./types";
import { Language, ManagerUser } from "../../internal-content-types";
import { EncodedContentTypeSchema } from "../../lib/ContentType";
import {
  accountInfoOutput,
  confirmTotpInput,
  createFolderInput,
  createFolderOutput,
  deleteFolderInput,
  deleteFolderOutput,
  createInput,
  deleteInput,
  deleteSessionInput,
  enrollTotpOutput,
  finalizeUploadInput,
  finalizeUploadOutput,
  getInput,
  getMediaUrlInput,
  getMediaUrlOutput,
  listFoldersInput,
  listFoldersOutput,
  listInput,
  listLiteralsInput,
  listLiteralsOutput,
  listOutput,
  loginInput,
  loginOutput,
  logoutOutput,
  prepareUploadInput,
  prepareUploadOutput,
  setDefaultLanguageInput,
  updateInput,
  updatePasswordInput,
  upsertLiteralInput,
  upsertLiteralOutput,
  verifyTotpInput,
  verifyTotpOutput,
  webauthnAuthOptionsInput,
  webauthnAuthOptionsOutput,
  webauthnAuthVerifyInput,
  webauthnAuthVerifyOutput,
  webauthnRegisterOptionsInput,
  webauthnRegisterOptionsOutput,
  webauthnRegisterVerifyInput,
} from "../../contracts";
import { apiOperationsOutput } from "../../schemas/manager/apiOperations";

const okOutput = z.object({ ok: z.boolean() });

export const createManagerOperationContracts = () =>
  ({
    "manager.contentTypes": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get all content types without schema",
      output: z.array(EncodedContentTypeSchema),
      method: "get",
    }),
    "manager.languages": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get all languages",
      output: z.array(Language.getOutputSchema()),
      method: "get",
    }),
    "manager.regenerateRoutes": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Regenerate all routes map",
      output: okOutput,
      method: "post",
    }),
    "manager.create": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Create a new entry for a content type",
      input: createInput,
      output: z.any(),
      method: "post",
    }),
    "manager.update": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description:
        "Update an entry for a content type, values with undefined are not modified, to erase a value set them to null",
      input: updateInput,
      output: z.any(),
      method: "post",
    }),
    "manager.delete": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Delete an entry for a content type",
      input: deleteInput,
      output: z.any(),
      method: "post",
    }),
    "manager.get": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get an entry for a content type",
      input: getInput,
      output: z.any(),
      method: "post",
    }),
    "manager.list": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List entries for a content type with query",
      input: listInput,
      output: listOutput,
      method: "post",
    }),
    "manager.setDefaultLanguage": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Set default language for the application",
      input: setDefaultLanguageInput,
      output: okOutput,
      method: "post",
    }),
    "manager.permissions": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get the list of all permissions",
      output: z.array(z.string()),
      method: "get",
    }),
    "manager.apiOperations": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get the API operation catalog",
      output: apiOperationsOutput,
      method: "get",
    }),
    "manager.media.prepareUpload": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Create a presigned upload URL for media",
      input: prepareUploadInput,
      output: prepareUploadOutput,
      method: "post",
    }),
    "manager.media.finalizeUpload": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Verify uploaded media and return metadata",
      input: finalizeUploadInput,
      output: finalizeUploadOutput,
      method: "post",
    }),
    "manager.media.getUrl": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get media URL (public or presigned)",
      input: getMediaUrlInput,
      output: getMediaUrlOutput,
      method: "post",
    }),
    "manager.media.createFolder": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Create media folder in current tree level",
      input: createFolderInput,
      output: createFolderOutput,
      method: "post",
    }),
    "manager.media.listFolders": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List media folders by parent folder",
      input: listFoldersInput,
      output: listFoldersOutput,
      method: "post",
    }),
    "manager.media.deleteFolder": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Recursively delete a media folder and its contents",
      input: deleteFolderInput,
      output: deleteFolderOutput,
      method: "post",
    }),
    "manager.literals.list": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List literal definitions and locale values",
      input: listLiteralsInput,
      output: listLiteralsOutput,
      method: "post",
    }),
    "manager.literals.upsert": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Create/update a literal translation value",
      input: upsertLiteralInput,
      output: upsertLiteralOutput,
      method: "post",
    }),
    "manager.auth.updatePassword": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Update the password of the current user",
      input: updatePasswordInput,
      output: okOutput,
      method: "post",
    }),
    "manager.auth.login": defineOperationContract({
      access: "public",
      kind: "mutation",
      description: "Login to the manager",
      input: loginInput,
      output: loginOutput,
      method: "post",
    }),
    "manager.auth.logout": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Logout of the manager",
      output: logoutOutput,
      method: "post",
    }),
    "manager.auth.getSession": defineOperationContract({
      access: "public",
      kind: "query",
      description: "Get the current manager session if it exists",
      output: ManagerUser.getOutputSchema().nullable(),
      method: "get",
    }),
    "manager.auth.accountInfo": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get account info including 2FA status and sessions",
      output: accountInfoOutput,
      method: "get",
    }),
    "manager.auth.deleteSession": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Delete specific sessions",
      input: deleteSessionInput,
      output: okOutput,
      method: "post",
    }),
    "manager.auth.totp.enroll": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Enroll TOTP for 2FA",
      output: enrollTotpOutput,
      method: "get",
    }),
    "manager.auth.totp.confirm": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Enable TOTP for the current user",
      input: confirmTotpInput,
      output: okOutput,
      method: "post",
    }),
    "manager.auth.totp.verify": defineOperationContract({
      access: "public",
      kind: "mutation",
      description: "Complete TOTP challenge",
      input: verifyTotpInput,
      output: verifyTotpOutput,
      method: "post",
    }),
    "manager.auth.webauthn.register.options": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get WebAuthn registration options",
      input: webauthnRegisterOptionsInput,
      output: webauthnRegisterOptionsOutput,
      method: "post",
    }),
    "manager.auth.webauthn.register.verify": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Verify WebAuthn registration",
      input: webauthnRegisterVerifyInput,
      output: okOutput,
      method: "post",
    }),
    "manager.auth.webauthn.auth.options": defineOperationContract({
      access: "public",
      kind: "query",
      description: "Get WebAuthn authentication options",
      input: webauthnAuthOptionsInput,
      output: webauthnAuthOptionsOutput,
      method: "post",
    }),
    "manager.auth.webauthn.auth.verify": defineOperationContract({
      access: "public",
      kind: "mutation",
      description: "Verify WebAuthn authentication",
      input: webauthnAuthVerifyInput,
      output: webauthnAuthVerifyOutput,
      method: "post",
    }),
  }) satisfies RakunOperationContractMap;
