/* eslint-disable @typescript-eslint/no-explicit-any */
import z from "zod";

import type { RakunOperationContractMap } from "./types";
import { defineOperationContract } from "./types";
import { Language, ManagerUser } from "../../internal-content-types";
import { EncodedContentTypeSchema } from "../../lib/ContentType";
import {
  linkedIteratorGetInput,
  linkedIteratorStateOutput,
} from "../../schemas/manager/linkedIterator";
import {
  accountInfoOutput,
  backupRecord,
  createCommentInput,
  createCommentOutput,
  toggleCommentReactionInput,
  toggleCommentReactionOutput,
  confirmTotpInput,
  createFolderInput,
  createFolderOutput,
  contentVersionRecord,
  contentTypeInput,
  deleteFolderInput,
  deleteFolderOutput,
  createInput,
  createBackupInput,
  deleteInput,
  deleteSessionInput,
  duplicateInput,
  enrollTotpOutput,
  finalizeUploadInput,
  finalizeUploadOutput,
  getInput,
  getMediaUrlInput,
  getMediaUrlOutput,
  getVersionInput,
  listFoldersInput,
  listFoldersOutput,
  listBackupsOutput,
  listCommentsInput,
  listCommentsOutput,
  listFavoritesInput,
  listFavoritesOutput,
  localeVariantAssignInput,
  localeVariantCreateInput,
  localeVariantCreateOutput,
  localeVariantListInput,
  localeVariantListOutput,
  localeVariantUnassignInput,
  listMentionUsersOutput,
  listMigrationsOutput,
  listVersionsInput,
  listVersionsOutput,
  listInput,
  listLiteralsInput,
  listLiteralsOutput,
  listOutput,
  loginInput,
  loginOutput,
  logoutOutput,
  prepareUploadInput,
  prepareUploadOutput,
  createPreviewInput,
  createPreviewOutput,
  restoreBackupInput,
  restoreBackupOutput,
  restoreVersionInput,
  restoreVersionOutput,
  setDefaultLanguageInput,
  translateDocumentInput,
  translateDocumentOutput,
  toggleFavoriteInput,
  toggleFavoriteOutput,
  updateInput,
  updateAccountInput,
  updateTutorialPreferencesInput,
  markTourSeenInput,
  updatePasswordInput,
  upsertLiteralInput,
  upsertLiteralOutput,
  verifyTotpInput,
  verifyTotpOutput,
  webauthnAuthOptionsInput,
  webauthnAuthOptionsOutput,
  webauthnAuthVerifyInput,
  webauthnAuthVerifyOutput,
  webauthnRegisterOptionsInput,
  webauthnRegisterOptionsOutput,
  webauthnRegisterVerifyInput,
} from "../../contracts";
import { apiOperationsOutput } from "../../schemas/manager/apiOperations";

const okOutput = z.object({ ok: z.boolean() });

export const createManagerOperationContracts = () =>
  ({
    "manager.contentTypes": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get all content types without schema",
      output: z.array(EncodedContentTypeSchema),
      method: "get",
    }),
    "manager.contentType": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get one encoded content type by name",
      input: contentTypeInput,
      output: EncodedContentTypeSchema.nullable(),
      method: "post",
    }),
    "manager.languages": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get all languages",
      output: z.array(Language.getOutputSchema()),
      method: "get",
    }),
    "manager.regenerateRoutes": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Regenerate all routes map",
      output: okOutput,
      method: "post",
    }),
    "manager.create": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Create a new entry for a content type",
      input: createInput,
      output: z.any(),
      method: "post",
    }),
    "manager.duplicate": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Duplicate an entry for a content type",
      input: duplicateInput,
      output: z.any(),
      method: "post",
    }),
    "manager.update": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description:
        "Update an entry for a content type, values with undefined are not modified, to erase a value set them to null",
      input: updateInput,
      output: z.any(),
      method: "post",
    }),
    "manager.delete": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Permanently delete an entry for a content type",
      input: deleteInput,
      output: z.any(),
      method: "post",
    }),
    "manager.trash": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Move an entry for a content type to trash",
      input: deleteInput,
      output: z.any(),
      method: "post",
    }),
    "manager.get": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get an entry for a content type",
      input: getInput,
      output: z.any(),
      method: "post",
    }),
    "manager.linkedIterator.get": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get the effective linked iterator state for a content type",
      input: linkedIteratorGetInput,
      output: linkedIteratorStateOutput,
      method: "post",
    }),
    "manager.list": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List entries for a content type with query",
      input: listInput,
      output: listOutput,
      method: "post",
    }),
    "manager.favorites.list": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List favorite content documents for the current user",
      input: listFavoritesInput,
      output: listFavoritesOutput,
      method: "post",
    }),
    "manager.favorites.toggle": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Add or remove a favorite content document for the current user",
      input: toggleFavoriteInput,
      output: toggleFavoriteOutput,
      method: "post",
    }),
    "manager.localeVariants.list": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List locale variants for a routeable document group",
      input: localeVariantListInput,
      output: localeVariantListOutput,
      method: "post",
    }),
    "manager.localeVariants.create": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Create a locale variant document from an existing document",
      input: localeVariantCreateInput,
      output: localeVariantCreateOutput,
      method: "post",
    }),
    "manager.localeVariants.assign": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Assign locales to a locale variant document",
      input: localeVariantAssignInput,
      output: localeVariantListOutput,
      method: "post",
    }),
    "manager.localeVariants.unassign": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Remove locale assignments from a locale variant document",
      input: localeVariantUnassignInput,
      output: localeVariantListOutput,
      method: "post",
    }),
    "manager.users.mentions": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List manager users available for mentions",
      output: listMentionUsersOutput,
      method: "get",
    }),
    "manager.comments.list": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List comments for a content document",
      input: listCommentsInput,
      output: listCommentsOutput,
      method: "post",
    }),
    "manager.comments.create": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Create a comment for a content document",
      input: createCommentInput,
      output: createCommentOutput,
      method: "post",
    }),
    "manager.comments.toggleReaction": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Add or remove a reaction for a content comment",
      input: toggleCommentReactionInput,
      output: toggleCommentReactionOutput,
      method: "post",
    }),
    "manager.setDefaultLanguage": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Set default language for the application",
      input: setDefaultLanguageInput,
      output: okOutput,
      method: "post",
    }),
    "manager.permissions": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get the list of all permissions",
      output: z.array(z.string()),
      method: "get",
    }),
    "manager.backups.list": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List database backups",
      output: listBackupsOutput,
      method: "get",
    }),
    "manager.backups.create": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Create a database backup",
      input: createBackupInput,
      output: backupRecord,
      method: "post",
    }),
    "manager.backups.restore": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Restore a database backup",
      input: restoreBackupInput,
      output: restoreBackupOutput,
      method: "post",
    }),
    "manager.migrations.list": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List schema migration state and ledger",
      output: listMigrationsOutput,
      method: "get",
    }),
    "manager.versions.list": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List document versions",
      input: listVersionsInput,
      output: listVersionsOutput,
      method: "post",
    }),
    "manager.versions.get": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get a document version",
      input: getVersionInput,
      output: contentVersionRecord.nullable(),
      method: "post",
    }),
    "manager.versions.restore": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Restore a document version",
      input: restoreVersionInput,
      output: restoreVersionOutput,
      method: "post",
    }),
    "manager.translateDocument": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Translate supported translatable fields for a document",
      input: translateDocumentInput,
      output: translateDocumentOutput,
      method: "post",
    }),
    "manager.preview.create": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Create a temporary live preview snapshot",
      input: createPreviewInput,
      output: createPreviewOutput,
      method: "post",
    }),
    "manager.apiOperations": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get the API operation catalog",
      output: apiOperationsOutput,
      method: "get",
    }),
    "manager.media.prepareUpload": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Create a presigned upload URL for media",
      input: prepareUploadInput,
      output: prepareUploadOutput,
      method: "post",
    }),
    "manager.media.finalizeUpload": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Verify uploaded media and return metadata",
      input: finalizeUploadInput,
      output: finalizeUploadOutput,
      method: "post",
    }),
    "manager.media.getUrl": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get media URL (public or presigned)",
      input: getMediaUrlInput,
      output: getMediaUrlOutput,
      method: "post",
    }),
    "manager.media.createFolder": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Create media folder in current tree level",
      input: createFolderInput,
      output: createFolderOutput,
      method: "post",
    }),
    "manager.media.listFolders": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List media folders by parent folder",
      input: listFoldersInput,
      output: listFoldersOutput,
      method: "post",
    }),
    "manager.media.deleteFolder": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Recursively delete a media folder and its contents",
      input: deleteFolderInput,
      output: deleteFolderOutput,
      method: "post",
    }),
    "manager.literals.list": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "List literal definitions and locale values",
      input: listLiteralsInput,
      output: listLiteralsOutput,
      method: "post",
    }),
    "manager.literals.upsert": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Create/update a literal translation value",
      input: upsertLiteralInput,
      output: upsertLiteralOutput,
      method: "post",
    }),
    "manager.auth.updatePassword": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Update the password of the current user",
      input: updatePasswordInput,
      output: okOutput,
      method: "post",
    }),
    "manager.auth.login": defineOperationContract({
      access: "public",
      kind: "mutation",
      description: "Login to the manager",
      input: loginInput,
      output: loginOutput,
      method: "post",
    }),
    "manager.auth.logout": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Logout of the manager",
      output: logoutOutput,
      method: "post",
    }),
    "manager.auth.getSession": defineOperationContract({
      access: "public",
      kind: "query",
      description: "Get the current manager session if it exists",
      output: ManagerUser.getOutputSchema().nullable(),
      method: "get",
    }),
    "manager.auth.accountInfo": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get account info including 2FA status and sessions",
      output: accountInfoOutput,
      method: "get",
    }),
    "manager.auth.updateAccount": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Update the current manager account profile",
      input: updateAccountInput,
      output: ManagerUser.getOutputSchema(),
      method: "post",
    }),
    "manager.auth.updateTutorialPreferences": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Update tutorial onboarding preferences for the current user",
      input: updateTutorialPreferencesInput,
      output: ManagerUser.getOutputSchema(),
      method: "post",
    }),
    "manager.auth.markTourSeen": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Mark a manager tour as seen for the current user",
      input: markTourSeenInput,
      output: ManagerUser.getOutputSchema(),
      method: "post",
    }),
    "manager.auth.deleteSession": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Delete specific sessions",
      input: deleteSessionInput,
      output: okOutput,
      method: "post",
    }),
    "manager.auth.totp.enroll": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Enroll TOTP for 2FA",
      output: enrollTotpOutput,
      method: "get",
    }),
    "manager.auth.totp.confirm": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Enable TOTP for the current user",
      input: confirmTotpInput,
      output: okOutput,
      method: "post",
    }),
    "manager.auth.totp.verify": defineOperationContract({
      access: "public",
      kind: "mutation",
      description: "Complete TOTP challenge",
      input: verifyTotpInput,
      output: verifyTotpOutput,
      method: "post",
    }),
    "manager.auth.webauthn.register.options": defineOperationContract({
      access: "auth",
      kind: "query",
      description: "Get WebAuthn registration options",
      input: webauthnRegisterOptionsInput,
      output: webauthnRegisterOptionsOutput,
      method: "post",
    }),
    "manager.auth.webauthn.register.verify": defineOperationContract({
      access: "auth",
      kind: "mutation",
      description: "Verify WebAuthn registration",
      input: webauthnRegisterVerifyInput,
      output: okOutput,
      method: "post",
    }),
    "manager.auth.webauthn.auth.options": defineOperationContract({
      access: "public",
      kind: "query",
      description: "Get WebAuthn authentication options",
      input: webauthnAuthOptionsInput,
      output: webauthnAuthOptionsOutput,
      method: "post",
    }),
    "manager.auth.webauthn.auth.verify": defineOperationContract({
      access: "public",
      kind: "mutation",
      description: "Verify WebAuthn authentication",
      input: webauthnAuthVerifyInput,
      output: webauthnAuthVerifyOutput,
      method: "post",
    }),
  }) satisfies RakunOperationContractMap;
